version: '2'
services:
  artifactory:
    container_name: 'artifactory'
    hostname: 'artifactory'
    image: infra/artifactory
#	 environment:
#        networks:
    ports:
      - "18080:8081"
      - "1443:443"
    volumes:
      - /opt/volumes/artifactory/data/:/var/opt/jfrog/artifactory/data/
      - /opt/volumes/artifactory/etc/:/var/opt/jfrog/artifactory/etc/
      - /opt/volumes/artifactory/logs/:/var/opt/jfrog/artifactory/logs/
    
#END